apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tppa2f64m-go 
  janus-idp.io/tekton: tppa2f64m-go
  backstage.io/kubernetes-id: tppa2f64m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tppa2f64m-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  